### ISSUE TITLE
Incorrect dependency type for pickle

### ISSUE THREAD

**Issue by walrusVision** [erisata/exometer_graphite#1]
I was trying to use `exometer_graphite` in my project but unfortunately it looks like there is an error in the rebar config. `pickle` is referencing a commit hash but it marked as using `tag` instead of `ref`

This line
```erlang
    {pickle,        ".*", {git, "https://github.com/habibutsu/pickle.git",        {tag, "9a52dcd"}}},
```

needs to be changed to 
```erlang
    {pickle,        ".*", {git, "https://github.com/habibutsu/pickle.git",        {ref, "9a52dcd"}}},
```

**Comment by kape1395** [comment]
As I understand, this is incompatibility between the `rebar` and `rebar3`. Rebar uses `tag` for referencing a particular commit and does not support the `ref` notation. Rebar3 does the opposite. I'm not sure, how to make this compatible with both rebar versions (2.x and 3.x).

**Comment by walrusVision** [comment]
I have just had a quick look around, and although I haven't used it myself, it looks like getting something rebar2/rebar3 compatible using `rebar.config.script` might ([documented here](https://www.rebar3.org/v3/docs/from-rebar-2x-to-rebar3)) 

I'll try it out and see if I can get something to work.

**Comment by walrusVision** [comment]
That works as advertised and the following `rebar.config.script` will let me fetch the deps with rebar or rebar3

```erlang
case erlang:function_exported(rebar3, main, 1) of
    true -> % rebar3
        [{deps, [
            {lager,         {git, "https://github.com/basho/lager.git",             {tag, "3.2.1"}}}, % For exometer_core
            {exometer_core, {git, "https://github.com/Feuerlabs/exometer_core.git", {tag, "1.4"}}},
            {pickle,        {git, "https://github.com/habibutsu/pickle.git",        {ref, "9a52dcd"}}},
            {edown,         {git, "https://github.com/uwiger/edown.git",            {tag, "0.8.1"}}}
        ]} | lists:keydelete(deps, 1, CONFIG)];
    false -> % rebar 2.x
        CONFIG
end.

**Comment by kape1395** [comment]
Changed it a bit to avoid repeating the deps in the `rebar.config.script`. Pushed it to the master. Could you check, if it works OK for you?

**Comment by walrusVision** [comment]
That is working as a dependency in my rebar3 project now. Thanks!

**Comment by kape1395** [comment]
Thanks!
